#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

systemctl disable --now --quiet "$app-update.timer" 2>/dev/null || true
ynh_safe_rm "/etc/systemd/system/$app-update.timer"
ynh_config_remove_systemd "$app-update"
ynh_config_remove_nginx
ynh_config_remove_logrotate

# $data_dir (cache des open data, site publié) n'est supprimé qu'avec --purge
ynh_script_progression "Suppression de $app terminée"
